site_name: Build your code-first agent with Azure AI Foundry
docs_dir: lab_manual
nav:
  - Model Distillation Lab Manual | Teaching Small Models to Be Smart: index.md
  - Generate Training Data (15 min): Skillable_lab_manual1.md
  - Fine-tune and Optimize (15 min): Skillable_lab_manual2.md
  - Test Your ONNX Model (10 min): Skillable_lab_manual3.md
  - Register to Azure ML (5 min): Skillable_lab_manual4.md
  - Download the Model (5 min): Skillable_lab_manual5.md
  - Local Inference (10 min): Skillable_lab_manual6.md
  - Local Inference with Foundry Local (10 min): Skillable_lab_manual7.md
  - Conclusion: Skillable_lab_manualconclusion.md


plugins:
  - glightbox
  - include-markdown

theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky 
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default  # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - css/custom.css

# mkdocs.yml
extra_javascript:
  - js/custom-nav.js
